// @/lib/jobs/cache.ts
// An on-disk copy of every listing we've paid to extract.
//
// THIS EXISTS BECAUSE `npm run db:reset` WIPED 64 EXTRACTED LISTINGS.
//
// Jobs aren't seeded — they're ingested from live boards, and the expensive
// part is the model call that turns each description into weighted skill
// slugs. Dropping the database therefore threw away money, and the only way
// back was to pay again.
//
// So every successful ingest also writes here, and prisma/seed.ts restores
// from this file. A reset now costs nothing, the demo survives having no
// network, and a teammate cloning the repo gets the listings without paying.
//
// The file is committed deliberately. It's generated, which usually argues for
// gitignoring it — but it's generated by spending real money, and that makes
// it closer to content than to build output.

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';

import type { UpsertJobInput } from '@/prisma/queries';

/** Same shape `upsertJob` takes, so restoring is a straight replay. */
export type CachedJob = UpsertJobInput;

const CACHE_PATH = join(process.cwd(), 'data', 'jobs', 'ingested.json');

export function readJobCache(path = CACHE_PATH): CachedJob[] {
  if (!existsSync(path)) return [];

  try {
    const parsed = JSON.parse(readFileSync(path, 'utf8')) as unknown;
    return Array.isArray(parsed) ? (parsed as CachedJob[]) : [];
  } catch {
    // A corrupt cache must not break ingest or seeding — it's a convenience,
    // and the boards are still the source of truth.
    console.warn(`[jobs] ignoring unreadable cache at ${path}`);
    return [];
  }
}

/**
 * Merge new listings into the cache, keyed by id.
 *
 * Merge rather than overwrite: an ingest run only handles a batch, and the
 * cache has to accumulate across runs or each one would discard the last.
 * A re-extracted listing replaces its older copy, which is what `--refresh`
 * is for.
 */
export function writeJobCache(jobs: CachedJob[], path = CACHE_PATH): number {
  if (jobs.length === 0) return readJobCache(path).length;

  const byId = new Map(readJobCache(path).map((job) => [job.id, job]));
  for (const job of jobs) byId.set(job.id, job);

  // Sorted by id so the committed file has a stable diff instead of churning
  // on every run.
  const merged = [...byId.values()].sort((a, b) => a.id.localeCompare(b.id));

  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, `${JSON.stringify(merged, null, 2)}\n`);
  return merged.length;
}
